"""New mission

Revision ID: 2ab62b4f2d9a
Revises: ee3d4092b94b
Create Date: 2025-05-05 12:01:25.645832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab62b4f2d9a'
down_revision = 'ee3d4092b94b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer', sa.String(length=255), nullable=True))

    with op.batch_alter_table('new_church', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_church', schema=None) as batch_op:
        batch_op.drop_column('approval_status')

    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.drop_column('organizer')

    # ### end Alembic commands ###
