"""Update Church

Revision ID: 44aa0937a547
Revises: 486a2c27001f
Create Date: 2025-05-06 14:57:07.702622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44aa0937a547'
down_revision = '486a2c27001f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('church', schema=None) as batch_op:
        batch_op.drop_column('ward')

    with op.batch_alter_table('new_church', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_church', schema=None) as batch_op:
        batch_op.drop_column('county')

    with op.batch_alter_table('church', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ward', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
