"""New Church

Revision ID: 486a2c27001f
Revises: 2ab62b4f2d9a
Create Date: 2025-05-05 12:20:49.228446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486a2c27001f'
down_revision = '2ab62b4f2d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission', schema=None) as batch_op:
        batch_op.drop_column('approval_status')

    # ### end Alembic commands ###
