"""contact phone

Revision ID: 8b7b319b2eb6
Revises: c47bcf67b422
Create Date: 2025-02-11 16:47:56.425662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7b319b2eb6'
down_revision = 'c47bcf67b422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('church_update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('church_update', schema=None) as batch_op:
        batch_op.drop_column('contact_phone')

    # ### end Alembic commands ###
