"""New Locations

Revision ID: ee3d4092b94b
Revises: 8b7b319b2eb6
Create Date: 2025-05-04 21:46:49.856772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3d4092b94b'
down_revision = '8b7b319b2eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_type', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('long', sa.Float(), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('new_church',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('long', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('members', sa.Integer(), nullable=True),
    sa.Column('contact_phone', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('new_church')
    op.drop_table('mission')
    # ### end Alembic commands ###
